image: node-18-alpine


before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk update && apk add openssh-client bash
  - apk add python3 

stages:
  - build
  - run

# Job's name
build:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - npm install
    - npm run nest:build
  artifacts:
    paths:
      - node_modules

run:
  stage: run
  script:
    - node ./dist/main.js
  artifacts:
    paths:
      - node_modules/

second-job-parallel:
  stage: run
  script:
    - echo "I'm running at the same time as second-job!!!"