image: node-18-alpine

stages:
  - build
  - run

# Job's name
build:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - npm install
    - npm run nest:build
  artifacts:
    paths:
      - node_modules

run:
  stage: run
  script:
    - node ./dist/main.js
  artifacts:
    paths:
      - node_modules/

second-job-parallel:
  stage: run
  script:
    - echo "I'm running at the same time as second-job!!!"