version: "3.8"
services:
  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - local
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - minio
      - redis
  #    command:
  #      - node ./dist/main.js
  minio:
    image: minio/minio
    ports:
      - 9200:9200
      - 9000:9000
    volumes:
      - ./minio:/minio
    command: server ./minio --address :9000 --console-address :9200
    networks:
      - local
volumes:
  api:
    driver: local
  minio:
    driver: local
  redis:
    driver: local
networks:
  local:
