version: "3.8"
services:
  redis: # Name of container
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - local
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - ./src/environments/.env.docker
    volumes:
      - .:/usr/src/app
    container_name: knoxva-api
    ports:
      - 3000:3000
    depends_on:
      - minio
      - redis
    networks:
      - local
  #    command:
  #      - node ./dist/main.js
  minio:
    container_name: minio
    build:
      dockerfile: Dockerfile
      context: .
      target: MinioDeploy
    image: minio/minio
    ports:
      - 9000:9000
      - 9200:9200
    volumes:
      - ./minio:/usr/minio
    command: [
      "minio",
      "server",
      "/usr/minio",
      "--address",
      ":9000",
      "--console-address",
      ":9200"
    ]
    networks:
      - local
volumes:
  api:
    driver: local
  minio:
    driver: local
  redis:
    driver: local
networks:
  local: