import e from "express";

export enum CONFIG_NAME {
    MINIO_ENDPOINT = "MINIO_ENDPOINT",
    MINIO_PORT = "MINIO_PORT",
    MINIO_USESSL = "MINIO_USESSL",
    MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY",
    MINIO_SECRET_KEY = "MINIO_SECRET_KEY",
    REDIS_HOST = "REDIS_HOST",
    REDIS_PORT = "REDIS_PORT",
    SERVER_HOST = "SERVER_HOST",
    SERVER_PORT = "SERVER_PORT",
    GEN_IMAGE_MAX_GENERATE_PER_JOB = "GEN_IMAGE_MAX_GENERATE_PER_JOB",
    GEN_IMAGE_QUEUE_NAME = "GEN_IMAGE_QUEUE_NAME",
    GEN_IMAGE_MINIO_BUCKET_NAME = "GEN_IMAGE_MINIO_BUCKET_NAME",
    GEN_IMAGE_LIMITER_MAX = "GEN_IMAGE_LIMITER_MAX",
    GEN_IMAGE_LIMITER_DURATION = "GEN_IMAGE_LIMITER_DURATION",
    GEN_IMAGE_ATTEMPTS = "GEN_IMAGE_ATTEMPTS",
    GEN_IMAGE_DELAY = "GEN_IMAGE_DELAY",
    GEN_IMAGE_BACKOFF_TYPE = "GEN_IMAGE_BACKOFF_TYPE",
    GEN_IMAGE_BACKOFF_DELAY = "GEN_IMAGE_BACKOFF_DELAY",
    CHILD_MAX_RESTART_RAM = "CHILD_MAX_RESTART_RAM"
}

export enum VERSION {
    V1= '1',
    V2= '2'
}